---
platform: linux

image_resource:
    type: docker-image
    source:
        repository: openjdk
        tag: '8u191-jdk-alpine3.9'

inputs:
- name: spring-petclinic-microservices

caches:
- path: maven

run:
    path: spring-petclinic-microservices/ci/tasks/unit.sh